SELECT * FROM Soldier;
SELECT * FROM Pilot;
SELECT * FROM Technical_Engineer;
SELECT * FROM Airbase;
SELECT * FROM Squadron;
SELECT * FROM Flight;
SELECT * FROM Aircraft;
SELECT * FROM UAV;
SELECT * FROM Airplane;
