--
-- Target: Oracle 
-- Syntax: sqlplus user@tnsnames_entry/password @filename.sql
-- 
-- Date  : May 19 2024 23:30
-- Script Generated by Database Design Studio 2.21.3 
--



--
-- Create Table    : 'Soldier'   
-- First_Name      :  
-- Last_Name       :  
-- Rank            :  
-- Brithdate       :  
-- ID              :  
--
CREATE TABLE Soldier (
    first_name     VARCHAR2(20) NOT NULL,
    last_name       VARCHAR2(20) NOT NULL,
    rank           VARCHAR2(10) NOT NULL,
    birthdate      DATE NOT NULL,
    id             NUMBER(38) NOT NULL,
CONSTRAINT pk_Soldier PRIMARY KEY (ID))
/


--
-- Create Table    : 'Aircraft'   
-- SerialID        :  
-- Production_Date :  
-- AmmunitionType  :  
-- Model           :  
--
CREATE TABLE Aircraft (
    serialid       NUMBER(38) NOT NULL,
    production_date DATE NOT NULL,
    ammunitiontype VARCHAR2(15) NOT NULL,
    model          VARCHAR2(15) NOT NULL,
CONSTRAINT pk_Aircraft PRIMARY KEY (SerialID))
/


--
-- Create Table    : 'Squadron'   
-- Squadron_Number :  
-- Suadron_Name    :  
-- Formation_Date  :  
--
CREATE TABLE Squadron (
    squadron_number NUMBER(38) NOT NULL,
    suadron_name   VARCHAR2(20) NOT NULL,
    formation_date DATE NOT NULL,
CONSTRAINT pk_Squadron PRIMARY KEY (Squadron_Number))
/


--
-- Create Table    : 'Pilot'   
-- ID              :  (references Soldier.ID)
-- Type            :  
-- Flight_Hours    :  
-- Call_Sign       :  
-- Squadron_Number :  (references Squadron.Squadron_Number)
--
CREATE TABLE Pilot (
    id             NUMBER(38) NOT NULL,
    type           VARCHAR2(10) NOT NULL,
    flight_hours   NUMBER(38) NOT NULL,
    call_sign      VARCHAR2(20) NOT NULL,
    squadron_number NUMBER(38) NOT NULL,
CONSTRAINT pk_Pilot PRIMARY KEY (ID),
CONSTRAINT fk_Pilot2 FOREIGN KEY (ID)
    REFERENCES Soldier (ID),
CONSTRAINT fk_Pilot FOREIGN KEY (Squadron_Number)
    REFERENCES Squadron (Squadron_Number)
    ON DELETE CASCADE)
/


--
-- Create Table    : 'Technical_Engineer'   
-- ID              :  (references Soldier.ID)
-- Degree          :  
-- Speciality      :  
-- LicenceNumber   :  
--
CREATE TABLE Technical_Engineer (
    id             NUMBER(38) NOT NULL,
    degree         VARCHAR2(20) NOT NULL,
    speciality     VARCHAR2(20) NOT NULL,
    licencenumber  NUMBER(38) NOT NULL UNIQUE,
CONSTRAINT pk_Technical_Engineer PRIMARY KEY (ID),
CONSTRAINT fk_Technical_Engineer FOREIGN KEY (ID)
    REFERENCES Soldier (ID))
/


--
-- Create Table    : 'UAV'   
-- SerialID        :  (references Aircraft.SerialID)
-- Battry          :  
-- Communication   :  
-- Control_Range   :  
--
CREATE TABLE UAV (
    serialid       NUMBER(38) NOT NULL,
    battry         NUMBER(38) NOT NULL,
    communication  VARCHAR2(20) NOT NULL,
    control_range  NUMBER(38) NOT NULL,
CONSTRAINT pk_UAV PRIMARY KEY (SerialID),
CONSTRAINT fk_UAV FOREIGN KEY (SerialID)
    REFERENCES Aircraft (SerialID))
/


--
-- Create Table    : 'Airplane'   
-- SerialID        :  (references Aircraft.SerialID)
-- Fuel            :  
-- Gforce_Limit    :  
-- Ejection_Seat_Capable :  
--
CREATE TABLE Airplane (
    serialid       NUMBER(38) NOT NULL,
    fuel           NUMBER(38) NOT NULL,
    gforce_limit   NUMBER(38) NOT NULL,
    ejection_seat_capable CHAR(1) NOT NULL,
CONSTRAINT pk_Airplane PRIMARY KEY (serialid),
CONSTRAINT fk_Airplane FOREIGN KEY (serialid)
    REFERENCES Aircraft (serialid))
/


--
-- Create Table    : 'Airbase'   
-- Name            :  
-- Capacity        :  
-- Location        :  
-- Squadron_Number :  (references Squadron.Squadron_Number)
-- Runway_Number   :  
--
CREATE TABLE Airbase (
    name           VARCHAR2(50) NOT NULL,
    capacity       NUMBER(38) NOT NULL,
    location       VARCHAR2(30) NOT NULL,
    squadron_number NUMBER(38) NOT NULL,
    runway_number  NUMBER(38) NOT NULL,
CONSTRAINT pk_Airbase PRIMARY KEY (Name),
CONSTRAINT fk_Airbase FOREIGN KEY (Squadron_Number)
    REFERENCES Squadron (Squadron_Number))
/


--
-- Create Table    : 'Flight'   
-- FlightId        :  
-- ID              :  (references Pilot.ID)
-- Name            :  (references Airbase.Name)
-- SerialID        :  (references Aircraft.SerialID)
-- Flight_Date     :  
-- Duration        :  
--
CREATE TABLE Flight (
    flightid       NUMBER(38) NOT NULL,
    id             NUMBER(38) NOT NULL,
    name           VARCHAR2(50) NOT NULL,
    serialid       NUMBER(38) NOT NULL,
    flight_date    DATE NOT NULL,
    duration       NUMBER(38) NOT NULL,
CONSTRAINT pk_Flight PRIMARY KEY (FlightId,ID,Name,SerialID),
CONSTRAINT fk_Flight FOREIGN KEY (ID)
    REFERENCES Pilot (ID)
    ON DELETE CASCADE,
CONSTRAINT fk_Flight2 FOREIGN KEY (Name)
    REFERENCES Airbase (Name)
    ON DELETE CASCADE,
CONSTRAINT fk_Flight3 FOREIGN KEY (SerialID)
    REFERENCES Aircraft (SerialID)
    ON DELETE CASCADE)
