select * from soldier;
select * from pilot;
select * from technical_engineer;
select * from squadron;
select * from airbase;
select * from aircraft;
select * from airplane;
select * from uav;
select * from flight;